{{- if .Values.paymentService.enabled }}
{{ include "smart-parking.renderDeployment" (dict "root" . "deployment" .Values.paymentService.deployment "service" .Values.paymentService.service) }}
{{- end }}
