services:
  mongo:
    image: mongo:7
    container_name: smart-parking-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  auth-service:
    build: ./auth-service
    container_name: auth-service
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - mongo
    ports:
      - "4001:4001"

  parking-service:
    build: ./parking-service
    container_name: parking-service
    env_file:
      - ./services/parking-service/.env
    depends_on:
      - mongo
    ports:
      - "4002:4002"

  booking-service:
    build: ./booking-service
    container_name: booking-service
    env_file:
      - ./services/booking-service/.env
    depends_on:
      - mongo
      - parking-service
      - notification-service
    ports:
      - "4003:4003"

  payment-service:
    build: ./payment-service
    container_name: payment-service
    env_file:
      - ./services/payment-service/.env
    depends_on:
      - mongo
      - booking-service
      - notification-service
    ports:
      - "4004:4004"

  scheduler-service:
    build: ./scheduler-service
    container_name: scheduler-service
    env_file:
      - ./services/scheduler-service/.env
    depends_on:
      - booking-service
    ports:
      - "4005:4005"

  notification-service:
    build: ./notification-service
    container_name: notification-service
    env_file:
      - ./services/notification-service/.env
    depends_on:
      - mongo
    ports:
      - "4006:4006"

  frontend:
    build: ./frontend
    container_name: smart-parking-frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - auth-service
      - parking-service
      - booking-service
      - payment-service
      - notification-service
    ports:
      - "5173:5173"

volumes:
  mongo_data:
