namespace: sps-ns

configMap:
  name: frontend-configmap
  data:
    VITE_AUTH_SERVICE_URL: "/auth"
    VITE_PARKING_SERVICE_URL: "/parking"
    VITE_BOOKING_SERVICE_URL: "/booking"
    VITE_PAYMENT_SERVICE_URL: "/payment"
    VITE_NOTIFICATION_SERVICE_URL: "/notification"
    VITE_RAZORPAY_KEY_ID: "rzp_test_ShFFMxa9JkqmZu"

deployment:
  name: frontend-deploy
  replicas: 2
  selectorLabels:
    app: sps-frontend
  podLabels:
    app: sps-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  containers:
    - name: frontend-container
      image:
        repository: nimeshsv814/frontend
        tag: v1.1.3
      ports:
        - containerPort: 80
      envFromConfigMaps:
        - frontend-configmap
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "200m"
          memory: "512Mi"

service:
  name: frontend-svc
  selectorLabels:
    app: sps-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
