apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-configmap
  namespace: sps-ns
data:
  PORT: "4003"
  MONGO_URI: "mongodb://mongo-svc:27017/bookingdb"
  JWT_SECRET: "smartparking_super_secret"
  CORS_ORIGIN: "*"
  PARKING_SERVICE_URL: "http://parking-service:4002"
  NOTIFICATION_SERVICE_URL: "http://notification-service:4006"
  INTERNAL_API_KEY: "smartparking_internal_key"
  BOOKING_HOLD_MINUTES: "10"

