{{- if .Values.notificationService.enabled }}
{{ include "smart-parking.renderDeployment" (dict "root" . "deployment" .Values.notificationService.deployment "service" .Values.notificationService.service) }}
{{- end }}
