apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deploy
  namespace: sps-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sps-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sps-scheduler
    spec:
      containers:
        - name: scheduler-container
          image: nimeshsv814/scheduler-service:v1.0.0
          ports:
            - containerPort: 4005
          envFrom:
            - configMapRef:
                name: scheduler-configmap
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"