apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-deploy
  namespace: sps-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sps-parking
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sps-parking
    spec:
      containers:
        - name: parking-container
          image: nimeshsv814/parking-service:v1.0.0
          ports:
            - containerPort: 4002
          envFrom:
            - configMapRef:
                name: parking-configmap
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"