namespace: sps-ns

configMap:
  name: scheduler-configmap
  data:
    PORT: "4005"
    BOOKING_SERVICE_URL: "http://booking-service"
    INTERNAL_API_KEY: "smartparking_internal_key"
    CRON_SCHEDULE: "* * * * *"

deployment:
  name: scheduler-deploy
  replicas: 2
  selectorLabels:
    app: sps-scheduler
  podLabels:
    app: sps-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  containers:
    - name: scheduler-container
      image:
        repository: nimeshsv814/scheduler-service
        tag: v1.0.0
      ports:
        - containerPort: 4005
      envFromConfigMaps:
        - scheduler-configmap
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "200m"
          memory: "512Mi"

service:
  name: scheduler-service
  selectorLabels:
    app: sps-scheduler
  ports:
    - port: 80
      targetPort: 4005
  type: ClusterIP
