apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulSet.name }}
  namespace: {{ include "mongo.namespace" . }}
spec:
  replicas: {{ .Values.statefulSet.replicas }}
  minReadySeconds: {{ .Values.statefulSet.minReadySeconds }}
  selector:
    matchLabels:
{{ toYaml .Values.statefulSet.selectorLabels | nindent 6 }}
  template:
    metadata:
      labels:
{{ toYaml .Values.statefulSet.podLabels | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.statefulSet.terminationGracePeriodSeconds }}
      containers:
{{- range .Values.statefulSet.containers }}
        - name: {{ .name }}
          image: {{ include "mongo.image" .image }}
{{- if .ports }}
          ports:
{{- range .ports }}
            - containerPort: {{ .containerPort }}
{{- end }}
{{- end }}
{{- if .resources }}
          resources:
{{ toYaml .resources | nindent 12 }}
{{- end }}
{{- if .volumeMounts }}
          volumeMounts:
{{ toYaml .volumeMounts | nindent 12 }}
{{- end }}
{{- end }}
  volumeClaimTemplates:
{{ toYaml .Values.statefulSet.volumeClaimTemplates | nindent 4 }}
