namespace: sps-ns

configMap:
  name: payment-configmap
  data:
    PORT: "4004"
    MONGO_URI: "mongodb://mongo-svc:27017/paymentdb"
    JWT_SECRET: "smartparking_super_secret"
    CORS_ORIGIN: "*"
    BOOKING_SERVICE_URL: "http://booking-service"
    NOTIFICATION_SERVICE_URL: "http://notification-service"
    INTERNAL_API_KEY: "smartparking_internal_key"
    RAZORPAY_KEY_ID: "rzp_test_ShFFMxa9JkqmZu"
    RAZORPAY_KEY_SECRET: "1I4sLVIvCMWSTUlM5lCZm71j"

deployment:
  name: payment-deploy
  replicas: 2
  selectorLabels:
    app: sps-payment
  podLabels:
    app: sps-payment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  containers:
    - name: payment-container
      image:
        repository: nimeshsv814/payment-service
        tag: v1.0.1
      ports:
        - containerPort: 4004
      envFromConfigMaps:
        - payment-configmap
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "200m"
          memory: "512Mi"

service:
  name: payment-service
  selectorLabels:
    app: sps-payment
  ports:
    - port: 80
      targetPort: 4004
  type: ClusterIP
