namespace: sps-ns

configMap:
  name: parking-configmap
  data:
    PORT: "4002"
    MONGO_URI: "mongodb://mongo-svc:27017/parkingdb"
    JWT_SECRET: "smartparking_super_secret"
    CORS_ORIGIN: "*"
    INTERNAL_API_KEY: "smartparking_internal_key"

deployment:
  name: parking-deploy
  replicas: 2
  selectorLabels:
    app: sps-parking
  podLabels:
    app: sps-parking
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  containers:
    - name: parking-container
      image:
        repository: nimeshsv814/parking-service
        tag: v1.0.0
      ports:
        - containerPort: 4002
      envFromConfigMaps:
        - parking-configmap
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "200m"
          memory: "512Mi"

service:
  name: parking-service
  selectorLabels:
    app: sps-parking
  ports:
    - port: 80
      targetPort: 4002
  type: ClusterIP
