namespace: sps-ns

configMap:
  name: notification-configmap
  data:
    PORT: "4006"
    MONGO_URI: "mongodb://mongo-svc:27017/notificationdb"
    JWT_SECRET: "smartparking_super_secret"
    CORS_ORIGIN: "*"
    INTERNAL_API_KEY: "smartparking_internal_key"

deployment:
  name: notification-deploy
  replicas: 2
  selectorLabels:
    app: sps-notification
  podLabels:
    app: sps-notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  containers:
    - name: notification-container
      image:
        repository: nimeshsv814/notification-service
        tag: v1.0.0
      ports:
        - containerPort: 4006
      envFromConfigMaps:
        - notification-configmap
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "200m"
          memory: "512Mi"

service:
  name: notification-service
  selectorLabels:
    app: sps-notification
  ports:
    - port: 80
      targetPort: 4006
  type: ClusterIP
