namespace: sps-ns

configMap:
  name: booking-configmap
  data:
    PORT: "4003"
    MONGO_URI: "mongodb://mongo-svc:27017/bookingdb"
    JWT_SECRET: "smartparking_super_secret"
    CORS_ORIGIN: "*"
    PARKING_SERVICE_URL: "http://parking-service"
    NOTIFICATION_SERVICE_URL: "http://notification-service"
    INTERNAL_API_KEY: "smartparking_internal_key"
    BOOKING_HOLD_MINUTES: "10"

deployment:
  name: booking-deploy
  replicas: 2
  selectorLabels:
    app: sps-booking
  podLabels:
    app: sps-booking
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  containers:
    - name: booking-container
      image:
        repository: nimeshsv814/booking-service
        tag: v1.0.0
      ports:
        - containerPort: 4003
      envFromConfigMaps:
        - booking-configmap
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "200m"
          memory: "512Mi"

service:
  name: booking-service
  selectorLabels:
    app: sps-booking
  ports:
    - port: 80
      targetPort: 4003
  type: ClusterIP
